### PR TITLE
fix: vultr installation

### PR DESCRIPTION
**Pull request by Seven45**
## Description
bump `kubernetes_version` from `v1.28.2+1` to `v1.28.9+1`

## Related Issue(s)

Fixes https://github.com/kubefirst/kubefirst/issues/2261

### CODE REVIEW

**Comment by fharper** [comment]
FYI, @jokestax is fixing something else for Vultr that need to be fixed before we can test this PR. Once it's done, he will also test this one.

**Comment by fharper** [comment]
[His PR](https://github.com/kubefirst/kubefirst-api/pull/397) was merged, so I'll be able to test this one.

**Comment by fharper** [comment]
I'll need to give it another try tomorrow. I had an issue that isn't related to this PR.

**Comment by jokestax** [comment]
@fharper @Seven45  the issue is fixed in #794

**Comment by jokestax** [comment]
@fharper that pr solves the issue,i have upgraded it to 1.30,so you can test that branch itself:)

**Comment by fharper** [comment]
@Seven45 so sorry but someone else on the team updated the Kubernetes version by fixing another issue, which mean this PR has now no changes, or would have been a version lower than what we decided to use.

I'm so sorry, would have love to merge your commit as a contributor. With that said, thanks a lot for this PR as it helped us find that Vultr wasn't working anymore. We are implementing better daily testing to ensure this does not happen anymore.

Even if I need to close this PR, I consider you a contributor, and would love to send you some swag as a token of our appreciation. Can you ping me on our [Slack community](https://kubefirst.io/slack) (I'm @Fred) or by email at fred@kubefirst.io.

**Pull request closed without merging**
